### ISSUE TITLE
Andorra table generating duplicate jsons

### ISSUE THREAD

**Issue by junginseo** [mitmedialab/cityioserver#11]
a duplicate json is pushed every ~5 seconds with timestamp difference of ~50000 and a new id. 

"id":"-KqOjTNWTHDNAKRb1Nj0","objects":{"slider1":2,"toggle1":0,"toggle2":0,"toggle3":0,"toggle4":0,"dockID":-1,"dockRotation":0,"IDMax":15,"density":[7,21,20,18,16,32],"pop_young":0,"pop_mid":0,"pop_old":0},"timestamp":1501522945577

"id":"-KqOje28hYPtCKt7Cbx3","objects":{"slider1":2,"toggle1":0,"toggle2":0,"toggle3":0,"toggle4":0,"dockID":-1,"dockRotation":0,"IDMax":15,"density":[7,21,20,18,16,32],"pop_young":0,"pop_mid":0,"pop_old":0},"timestamp":1501522993361

**Comment by yasushisakai** [comment]
closing since I can't observe this behavior.
