### ISSUE TITLE
Mismatched table+masks/context data 

### ISSUE THREAD

**Issue by RELNO** [mitmedialab/cityioserver#16]
Rotation of camera, table or grid requires re-match of the grid to the masks files - which not sustainable for deployments

**Comment by yasushisakai** [comment]
?? details needed...
I need an example what the endpoint result should look like
is this an issue related to how the data is sent?

**Comment by RELNO** [comment]
@yasushisakai  -- the context , when separated from cityIO data is prone to errors. The consolidation we test right now should solve it. From endpoint point of view, it's just mean more data send/received. [also '?' in front of the question sounds more reasonable]

**Comment by yasushisakai** [comment]
closing
