### ISSUE TITLE
Wrong link to the the table on the home page

### ISSUE THREAD

**Issue by agrignard** [mitmedialab/cityioserver#8]
When clicking to any table on the home page we are redirected to 
https://cityio.media.mit.edu/table/citymatrix_volpe

should be
https://cityio.media.mit.edu/api/table/citymatrix_volpe

**Comment by yasushisakai** [comment]
- this was fixed in latest master 44074d0
- current media lab running older commit b6b32fd

-> not entirely sure if I should update the working server now...
** This issue will be closed as soon as the server has been updated **

**Comment by yasushisakai** [comment]
fixed
